apiVersion: v1
kind: Service
metadata:
  name: raven0
  namespace: raven0
  labels:
    app: raven0
spec:
  clusterIP: None
  selector:
    app: raven0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: raven0
 namespace: raven0
spec:
  serviceName: "raven0"
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: raven0
  template:
    metadata:
     name: raven0
     labels:
      app: raven0
    spec:
      containers:
      - name: raven0
        image: "artiefuzzz/raven0:kasagi-dev"
        resources:
          requests:
            cpu: "100m"
            memory: "256mi"
          limits:
            cpu: "200m"
            memory: "512mi"
