apiVersion: batch/v1
kind: Job
metadata:
  name: raven0
spec:
  replicas: 2
  template:
    metadata:
      name: raven0-Pod
    spec:
      containers:
      - name: raven0
        image: artiefuzzz/raven0
      restartPolicy: Never
