image: docker:latest

stages:
- build

variables:
 IMAGE: $CI_REGISTRY/$CI_IMAGE_PATH:$CI_IMAGE_REF_SLUG
 DEV_IMAGE: $CI_REGISTRY/$CI_IMAGE_PATH:$CI_IMAGE_REF_SLUG-dev

services:
  - docker:dind

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin $CI_REGISTRY

dev:
 stage: build
 script:
 - echo -n "$DEV_CONF" | base64 -d > config/main.json
 - docker build --tag $DEV_IMAGE .
 - docker push $DEV_IMAGE
 only:
 - nightly
 tags:
 - docker

production:
 stage: build
 script:
 - echo -n "$CONF" | base64 -d > config/main.json
 - docker build --tag $IMAGE .
 - docker push $IMAGE
 only:
 - main
 tags:
 - docker
